name: Build and Test

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies (back-end)
      run: |
        cd back-end
        dotnet restore

    - name: Build the back-end
      run: |
        cd back-end
        dotnet build

  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies (front-end)
      run: |
        cd front-end 
        npm install

    - name: Build the front-end
      run: |
        cd front-end
        npm run build
